# This workflow will build & upload a Python Package to TestPyPi using Twine 
# whenever a PR is merged or a commit is made to the master branch.

name: Build and Publish Package ðŸ“¦ to TestPyPi

# This workflow will run when a PR is merged or when a commit is made directly to the master branch.
# ref: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3
on: push

jobs:
  build-and-publish:
    name: Build and publish distributions to TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # æ›´æ–°åˆ°æœ€æ–°ç‰ˆæœ¬
    - name: Set up Python 3.7
      uses: actions/setup-python@v2  # æ›´æ–°åˆ°æœ€æ–°ç‰ˆæœ¬
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: python -m pip install build --user
    - name: ðŸ”¨Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/
    - name: Publish distribution ðŸ“¦ to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2  # æŒ‡å®šå…·ä½“ç‰ˆæœ¬
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
    - name: Publish distribution ðŸ“¦ to PyPI
      # if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.4.2  # æŒ‡å®šå…·ä½“ç‰ˆæœ¬
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}